# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Engage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Engage
  pod 'Firebase/Core'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseDatabase'


pod 'fluid-slider'
pod 'Charts'
pod '10Clock'

end
